# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_log', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
