# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170304_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_log',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
