# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170304_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_log',
            field=models.DateTimeField(null=True),
        ),
    ]
